# Generated by Django 3.2 on 2021-09-25 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0003_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
