# Generated by Django 3.2 on 2021-09-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0004_auto_20210925_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='screen_shot',
            new_name='screen',
        ),
        migrations.RemoveField(
            model_name='site',
            name='author',
        ),
    ]
