# Generated by Django 3.2 on 2021-09-26 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0005_auto_20210925_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='site',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
